#!/bin/bash

versione_attuale=$(uname -r)
versioni_disponibili=$(rpm -qa kernel | sort -V | tail -n 1 )
echo "versione corrente del kernel: $versione_attuale"
echo "ultima versione disponibile del kernel: $versioni_disponibili"
versione_attuale=$(echo $versione_attuale  | sed 's/kernel-//')
versioni_disponibili=$(echo $versioni_disponibili | sed 's/kernel-//')

if [ "$versione_attuale" == "$versioni_disponibili" ]; then

        echo    "questa è la versione più recente"
else
        echo    "non è la versione più recente"

fi
